### ISSUE TITLE
As frontend developer, Roy can you enhance the design of Topbar.

### ISSUE THREAD

**Issue by marktmng** [marktmng/sis_frontend#9]
- [x] Added color on Topbar
- [x] Fixed issue for the failed test
- [x]  Define Style Objects
- [x] Apply inline styles

**Comment by marktmng** [comment]
Hey frontend devloper can you start wroking please.

**Comment by Gilgamesh3379** [comment]
- [ ] Integration Testing
- [ ] Build Complete
